# Generated by Django 4.2.4 on 2024-01-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
